### PR TITLE
sections: only display after section start

### LINKED ISSUE #28: jumping to section doesn't work for lodash _.keys
so i disabled the telescope preview for now since the jumping to section doesn't work for that, and things are much better, but I noticed that jumping to the correct section, while it works for instance for lodash-4 `_.at`, or `_.gt` for instance, doesn't work for `_.keys`. I have no idea why.

Note that I use the glow integration (with latest git glow for performance).

### PR DESCRIPTION
**Pull request by emmanueltouzery**
fixes #28
It was wrong to give all the contents to the preview/display command and then search on the output, because the command could change the format completely.
So now we submit to the converter program only data after the section start, and we don't need to search the output anymore.

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
ideally we'd also drop the content after the next section start. That would make the output shorter, and consistent (only show for the current section), and it would also speed up display for glow massively. But I went for the quickfix for now.

**Comment by luckasRanarison** [comment]
This is a really interesting idea, making processing before rendering was a nice thought. But there's an issue with it, docs sections are not necessarily *headers*, it can also be a link, a word in the inside another section, etc... and in that case the docs would get cut without having the possibility to scroll up. It's a nice workaround though but we should check if the section is a header first and  use search as a fallback.

**Comment by emmanueltouzery** [comment]
interesting... but how would I know whether it's a header or not?

I printed the contents of `selection` in `open_doc`, and I get:
```lua

{
  display = "[lodash-4] _.keys",
  index = 1491,
  ordinal = "[lodash-4] _.keys",
  value = {
    alias = "lodash-4",
    link = "index#keys",
    name = "[lodash-4] _.keys",
    path = "1,### _.keys(object)[source](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L13305) [npm package](https://www.npmjs.com/package/lodash.keys)"
  }
}
```

I can't say here anything that tells me whether it's a header or not.

I have played a little also with converting the header text with glow to search for the converted header text. It would possibly be workable, but it's very messy, because glow emits shell escape codes for coloring. These would have to be stripped for searching. I in fact have some code to do that for some other project, but it just seems very frail...

**Comment by emmanueltouzery** [comment]
i think i have a better idea, hold on...

**Comment by emmanueltouzery** [comment]
I now opened an alternative PR, #45

Keeping this one open in case you still prefer the approach from this PR, after adaptations.

**Comment by luckasRanarison** [comment]
> interesting... but how would I know whether it's a header or not?
> 
> ```lua
> 
> {
>   ...
>   value = {
>     ...
>     path = "1,### _.keys(object)[source](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L13305) [npm package](https://www.npmjs.com/package/lodash.keys)"
>   }
> }
> ```

By header I meant markdown headers, starting with `#`. I think I prefer this PR approach, it could also be extended to omit next sections. I  honestly prefer making preprocessing like this instead of messing more with the transpiler. I gave up the idea of splitting the docs further because of the previous facts: sections not necessarily being headers and the nested sections. I don't want to add more complexity there just to fix some edge cases.

**Comment by emmanueltouzery** [comment]
I understand. None of the two PRs touch the transpiler, yes. For now I won't do anything because you wrote that you'll work on that. If I can help, let me know! And thank you for the plugin!

**Comment by luckasRanarison** [comment]
I'm also really thankful for all your help, I've learned so much with you :)

**Comment by luckasRanarison** [comment]
Also forget about section not being headers, I noticed this with bash docs but it still works and the docs are still concise enough even if the section start is left off.

**Comment by luckasRanarison** [comment]
The only remaining problem is piping command with the telescope previewer. Before I just used the filepath with the cmd (glow) but now we have to read the file first and pipe the filtered lines to the cmd and I don't know how.

```lua
local term_doc_previewer = previewers.new_termopen_previewer({
  title = "Preview",
  get_command = function(entry)
    local splited_path = vim.split(entry.value.path, ",")
    local file = splited_path[1]
    local file_path = path:new(plugin_config.dir_path, "docs", entry.value.alias, file .. ".md")
    local lines = file_path:readlines()
    local filtered_lines = operations.filter_doc(lines, splited_path[2])
    local args = {} -- TODO

    return args
  end,
})

```

**Comment by emmanueltouzery** [comment]
about the termopen issue, I'm optimistic. See
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/term_previewer.lua#L217

Telescope has a lot of options that you can see only in the code, not in the docs. Here we can see the `send_input` option. I think you can use it to send data to glow via stdin instead of giving a file name.

**Comment by emmanueltouzery** [comment]
more about the telescope previewer options, including `send_input`:
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/init.lua#L63

**Comment by emmanueltouzery** [comment]
some example of use of send_input: https://github.com/gallavee/search_results.nvim/blob/c8b2d9824a204227f429d9b1eac7d40b40d1ae75/plugin/main.lua#L147

**Comment by emmanueltouzery** [comment]
i think you'd call self.send_input in the preview callback.

**Comment by luckasRanarison** [comment]
> i think you'd call self.send_input in the preview callback
It'd too late, the string should be passed before the command, the simplest way to do this would be `echo "# Hello world" | glow -p` but we can't pipe command, I tried another approach without using termopen previewer but a normal buffer previewer and then output a job result like the kn normal preview buffer, but the lines get wrapped and the output is really messy.

**Comment by luckasRanarison** [comment]
> > i think you'd call self.send_input in the preview callback
It'd too late, the string should be passed before the command, the simplest way to do this would be `echo "# Hello world" | glow -p` but we can't pipe command, I tried another approach without using termopen previewer but a normal buffer previewer and then output a job result like the kn normal preview buffer, but the lines get wrapped and the output is really messy.

**Comment by emmanueltouzery** [comment]
I played with it a little, but didn't get very far for now. Maybe we should ask the telescope developers, I think they have a chat.

The approach I suggested yesterday is more the telescope low-level API, not higher-level like termopen or buffer previewers.

Piping would be possible also with termopen but it gets very ugly:
https://github.com/debugloop/telescope-undo.nvim/blob/3dec002ea3e7952071d26fbb5d01e2038a58a554/lua/telescope-undo/previewer.lua#L27

Another option possibly could be to create a temporary file, pass it to glow, overwrite it every time, then deleting it in the teardown callback maybe? Although teardown is available to the buffer previewer but not to the termopen previewer.

Maybe you can make a branch with the buffer previewer attempt. Possibly we could check what does the termopen previewer does differently from the buffer previewer, maybe it's possible to fix the wrapping...

**Comment by emmanueltouzery** [comment]
> Maybe you can make a branch with the buffer previewer attempt
i meant so that maybe i can try to play with it. Although I can't guarantee i'll have time to work on it very soon.

**Comment by emmanueltouzery** [comment]
Otherwise it's this gets really messy I'd possibly reconsider generating "cut files" at fetching time, after the transpiling. It would be a second pass, not touching the existing transpiling code.

**Comment by luckasRanarison** [comment]
> Maybe you can make a branch with the buffer previewer attempt. Possibly we could check what does the termopen previewer does differently from the buffer previewer, maybe it's possible to fix the wrapping...
https://github.com/luckasRanarison/nvim-devdocs/tree/telescope-previewer
In this version I sent the job result to the picker preview buffer instead of using termopen_preview, the same method used for rendering the docs before. And so the pager -p arg is no longer needed. I've never realized but even before the lines got wrapped but with this version there are extra lines for some reason.

**Comment by luckasRanarison** [comment]
Oh wait, I'm dumb. It actually works the extra lines were added because I used the same args for the normal previewer and picker previewer and the -w was set to 97 which caused extra lines!

**Comment by luckasRanarison** [comment]
We finally did it!!!

**Comment by emmanueltouzery** [comment]
:tada: :rocket: :dancers:

**Comment by emmanueltouzery** [comment]
fantastic, looking forward to testing this tonight and i'm super optimistic that this is it :tada:

**Comment by luckasRanarison** [comment]
🚀 👯 🎉 :) 
I forgot to specify the change with the picker cmd args in the commit description lol.

**Pull request merged**
